(()=>{"use strict";
const KEY="dewify:website-builder:v2";
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const uid=p=>`${p}-${Math.random().toString(36).slice(2,9)}`;
const palettes=[
{name:"Lavender",accent:"#7046ff",bg:"#ffffff",soft:"#f0ebff",text:"#16151b"},
{name:"Mono",accent:"#34343b",bg:"#ffffff",soft:"#f0f0f2",text:"#17171b"},
{name:"Blue",accent:"#326cff",bg:"#ffffff",soft:"#eaf0ff",text:"#172033"},
{name:"Emerald",accent:"#1f9d73",bg:"#ffffff",soft:"#e7f7f1",text:"#10201a"},
{name:"Rose",accent:"#e05c8c",bg:"#ffffff",soft:"#fff0f5",text:"#24151b"}
];
const defaults={header:{padding:24,minHeight:72},hero:{padding:72,minHeight:430},features:{padding:58,minHeight:260},products:{padding:58,minHeight:310},cta:{padding:48,minHeight:220},about:{padding:58,minHeight:260},contact:{padding:58,minHeight:320},faq:{padding:58,minHeight:300},footer:{padding:27,minHeight:72},image:{padding:40,minHeight:300},spacer:{padding:0,minHeight:180},divider:{padding:24,minHeight:80}};
function page(id,name){return{id,name,texts:{},links:{},sections:[{id:uid("header"),type:"header"},{id:uid("hero"),type:"hero"},{id:uid("features"),type:"features"},{id:uid("products"),type:"products"},{id:uid("footer"),type:"footer"}]}}
const base={projectName:"My Store",pages:[page("home","Home")],activePage:"home",accent:"#7046ff",palette:"Lavender",device:"desktop",zoom:1,selected:null,selectedElement:null,history:[],future:[]};
function migrate(s){if(!s)return structuredClone(base);s.pages??=base.pages;s.pages.forEach(p=>{p.texts??={};p.links??={};p.sectionStyles??={};p.sections??=[];p.sections.forEach(x=>{x.id??=uid(x.type);x.type??="features";x.texts??={};x.links??={};x.buttonTexts??={}})});return {...base,...s,history:[],future:[],selected:null,selectedElement:null}}
function load(){try{const s=JSON.parse(localStorage.getItem(KEY)||localStorage.getItem("dewify:website-builder:v1"));return migrate(s)}catch{return structuredClone(base)}}
let state=load(),tab="style",renameTarget=null,saveTimer=null;
const active=()=>state.pages.find(p=>p.id===state.activePage)||state.pages[0];
const findSec=id=>active().sections.find(s=>s.id===id);
const secStyle=s=>({...defaults[s.type]||defaults.features,...(active().sectionStyles?.[s.id]||{})});
const selected=()=>state.selected?findSec(state.selected):null;
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function snap(){return JSON.parse(JSON.stringify({...state,history:[],future:[],selected:null,selectedElement:null}))}
function commit(){state.history.push(snap());if(state.history.length>50)state.history.shift();state.future=[]}
function save(){localStorage.setItem(KEY,JSON.stringify({...state,history:[],future:[],selected:null,selectedElement:null}));$("#saveStatus").textContent="Saved just now"}
function dirty(){clearTimeout(saveTimer);$("#saveStatus").textContent="Unsaved changes";saveTimer=setTimeout(save,350)}
function toast(t){const x=$("#toast");x.textContent=t;x.classList.add("show");clearTimeout(x._t);x._t=setTimeout(()=>x.classList.remove("show"),1600)}
function setSelected(secId,el=null){state.selected=secId;state.selectedElement=el;renderCanvas();renderInspector()}
function addSection(type){commit();const p=active(),idx=Math.max(1,p.sections.length-1),s={id:uid(type),type,texts:{},links:{},buttonTexts:{}};p.sections.splice(idx,0,s);state.selected=s.id;state.selectedElement=null;dirty();render();toast(`${type[0].toUpperCase()+type.slice(1)} section added`)}
function deleteSection(id){const s=findSec(id);if(!s||["header","footer"].includes(s.type)){toast("Header and footer stay in every page");return}commit();active().sections=active().sections.filter(x=>x.id!==id);delete active().sectionStyles[id];state.selected=null;state.selectedElement=null;dirty();render();toast("Section deleted")}
function duplicateSection(id){const s=findSec(id);if(!s)return;commit();const copy=JSON.parse(JSON.stringify(s));copy.id=uid(s.type);active().sections.splice(active().sections.findIndex(x=>x.id===id)+1,0,copy);if(active().sectionStyles?.[id])active().sectionStyles[copy.id]={...active().sectionStyles[id]};state.selected=copy.id;state.selectedElement=null;dirty();render();toast("Section duplicated")}
function openPageModal(){closeMenus();$("#pageModal").classList.remove("hidden");$("#pageNameInput").value="";setTimeout(()=>$("#pageNameInput").focus(),20)}
function createPage(){const n=$("#pageNameInput").value.trim();if(!n)return toast("Give the page a name");if(state.pages.some(p=>p.name.toLowerCase()===n.toLowerCase()))return toast("That page already exists");commit();const p=page(uid("page"),n);state.pages.push(p);state.activePage=p.id;state.selected=null;state.selectedElement=null;closeModals();dirty();render();toast("Page created")}
function openRename(p){renameTarget=p;closeMenus();$("#renamePageInput").value=p.name;$("#renameModal").classList.remove("hidden");setTimeout(()=>$("#renamePageInput").select(),20)}
function renamePage(){const n=$("#renamePageInput").value.trim();if(!renameTarget||!n)return;if(state.pages.some(p=>p.id!==renameTarget.id&&p.name.toLowerCase()===n.toLowerCase()))return toast("That page already exists");commit();renameTarget.name=n;renameTarget=null;closeModals();dirty();render();toast("Page renamed")}
function deletePage(p){if(state.pages.length===1)return toast("A site needs at least one page");if(p.id==="home")return toast("Rename Home instead of deleting it");commit();state.pages=state.pages.filter(x=>x.id!==p.id);if(state.activePage===p.id)state.activePage=state.pages[0].id;state.selected=null;state.selectedElement=null;dirty();render();toast("Page deleted")}
function duplicatePage(p){commit();const copy=JSON.parse(JSON.stringify(p));copy.id=uid("page");copy.name=`${p.name} copy`;state.pages.push(copy);state.activePage=copy.id;state.selected=null;state.selectedElement=null;dirty();render();toast("Page duplicated")}
function closeModals(){$$(".modal-backdrop").forEach(x=>x.classList.add("hidden"));renameTarget=null}
function closeMenus(){$$(".wb-context-menu").forEach(x=>x.remove())}
function undo(){const old=state.history.pop();if(!old)return;state.future.push(snap());state={...old,history:state.history,future:state.future};save();render();toast("Undone")}
function redo(){const next=state.future.pop();if(!next)return;state.history.push(snap());state={...next,history:state.history,future:state.future};save();render();toast("Redone")}
function applyPageLink(sec,key,value){const s=findSec(sec);if(!s)return;commit();s.links??={};if(value)s.links[key]=value;else delete s.links[key];dirty();render();toast(value?"Link set":"Link removed")}
function linkTarget(sec,key){return findSec(sec)?.links?.[key]||""}
function goToTarget(sec,key){const target=linkTarget(sec,key);if(!target){showContext(sec,key);return}state.activePage=target;state.selected=null;state.selectedElement=null;render();dirty()}
function readImage(file,secId){if(!file)return;const s=findSec(secId);const r=new FileReader();r.onload=()=>{commit();s.image=r.result;dirty();render();toast("Image added")};r.readAsDataURL(file)}
function editTextNode(node,secId){const s=findSec(secId);if(!s)return;const key=node.dataset.key||"text";commit();node.contentEditable="true";node.focus();document.execCommand("selectAll",false,null);const finish=()=>{node.contentEditable="false";s.texts??={};s.texts[key]=node.textContent.trim();save();render()};node.addEventListener("blur",finish,{once:true});node.addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();node.blur()}},{once:true})}
function makeText(s,key,fallback,cls="canvas-edit-text"){return `<span class="${cls}" data-edit-text data-key="${key}">${esc(s.texts?.[key]??fallback)}</span>`}
function styleSection(el,s){const st=secStyle(s);el.style.minHeight=`${st.minHeight}px`;el.style.paddingTop=`${st.padding}px`;el.style.paddingBottom=`${st.padding}px`;el.dataset.width=st.width||"center"}
function sectionMarkup(s){const t=k=>makeText(s,k,{brand:"YOUR BRAND",kicker:"PREMIUM DIGITAL PRODUCTS",headline:"Build Your Dreams Digitally",body:"Create a beautiful storefront, portfolio or landing page without touching code.",title:"Everything you need to launch.",subtitle:"A clean system for people who care about the final result.",left:"© 2026 YOUR BRAND",right:"Built with DEWIFY"}[k]||k);
if(s.type==="header")return `<strong class="site-brand-edit">${t("brand","")}</strong><nav class="site-nav-edit"></nav>`;
if(s.type==="hero")return `<div><span class="site-kicker">${t("kicker","")}</span><h2>${t("headline","")}</h2><p>${t("body","")}</p><div class="hero-actions-edit"><button class="hero-button-edit" data-link="true" data-link-key="hero-1">${esc(s.buttonTexts?.["hero-1"]??"Explore products →")}</button><button class="hero-button-edit secondary" data-link="true" data-link-key="hero-2">${esc(s.buttonTexts?.["hero-2"]??"Learn more")}</button></div></div><div class="hero-visual"><div class="hero-visual-copy"><small>LIVE PREVIEW</small><strong>Make it yours.</strong></div></div>`;
if(s.type==="features")return `<span class="site-kicker">WHY IT WORKS</span><h3 class="feature-title">${t("title","")}</h3><p class="feature-subtitle">${t("subtitle","")}</p><div class="feature-grid-edit">${["Fast setup","Beautiful by default","Fully editable","Mobile ready"].map((x,k)=>`<article class="feature-card-edit"><div class="feature-icon-edit">${["↯","✦","◇","⌁"][k]}</div><strong data-edit-text data-key="feature-${k}">${esc(s.texts?.[`feature-${k}`]??x)}</strong><p data-edit-text data-key="feature-p-${k}">${esc(s.texts?.[`feature-p-${k}`]??"Simple controls. No code required.")}</p></article>`).join("")}</div>`;
if(s.type==="products")return `<div class="section-heading-row"><div><span class="site-kicker">FEATURED</span><h3>${t("title","Popular picks")}</h3><p>${t("subtitle","Swap these cards for your own products later.")}</p></div><button class="product-link" data-link="true" data-link-key="products-all">${esc(s.buttonTexts?.["products-all"]??"View all →")}</button></div><div class="product-grid-edit">${["Creator Vault","AI Money Arc","Crate 100"].map((x,k)=>`<article class="product-card-edit"><div class="product-art-edit ${k===1?"two":k===2?"three":""}"></div><div class="product-copy-edit"><small>0${k+1} / DIGITAL</small><strong data-edit-text data-key="product-${k}">${esc(s.texts?.[`product-${k}`]??x)}</strong><span data-edit-text data-key="price-${k}">${esc(s.texts?.[`price-${k}`]??["₹399","₹299","₹199"][k])}</span></div></article>`).join("")}</div>`;
if(s.type==="cta")return `<div class="cta-inner"><span class="site-kicker">READY WHEN YOU ARE</span><h2>${t("headline","Turn the idea into a website.")}</h2><p>${t("body","One page or ten. Your site stays yours.")}</p><button class="hero-button-edit" data-link="true" data-link-key="cta">${esc(s.buttonTexts?.cta??"Get started →")}</button></div>`;
if(s.type==="about")return `<div class="feature-section-inner"><span class="site-kicker">ABOUT</span><h3 class="feature-title">${t("title","A little about the brand.")}</h3><p class="feature-subtitle">${t("subtitle","Tell visitors who you are, what you make and why they should care.")}</p></div>`;
if(s.type==="contact")return `<div class="feature-section-inner"><span class="site-kicker">CONTACT</span><h3 class="feature-title">${t("title","Let's talk.")}</h3><div class="contact-form-edit"><input placeholder="Name"><input placeholder="Email"><textarea placeholder="Message"></textarea><button class="hero-button-edit">Send message</button></div></div>`;
if(s.type==="faq")return `<div class="feature-section-inner"><span class="site-kicker">FAQ</span><h3 class="feature-title">${t("title","Questions, answered.")}</h3><div class="faq-list-edit">${["How does it work?","Can I add more pages?","Is mobile supported?"].map((q,k)=>`<details><summary data-edit-text data-key="faq-${k}">${esc(s.texts?.[`faq-${k}`]??q)}</summary><p>Click the question to preview the answer.</p></details>`).join("")}</div></div>`;
if(s.type==="image")return `<div class="uploaded-image-section"><label class="image-drop"><span>+</span><strong>Upload image</strong><small>Click or drop an image here</small><input class="section-image-input" type="file" accept="image/*"></label>${s.image?`<img src="${s.image}" alt="" class="uploaded-image">`:""}</div>`;
if(s.type==="spacer")return `<div class="spacer-section-label">Spacer · ${secStyle(s).minHeight}px</div>`;
if(s.type==="divider")return `<div class="divider-section-line"></div>`;
return `<div class="feature-section-inner"><span class="site-kicker">CUSTOM SECTION</span><h3 class="feature-title">${t("title","Make this section yours.")}</h3><p class="feature-subtitle">${t("subtitle","Edit the text and adjust the spacing from the inspector.")}</p></div>`}
function renderPages(){const box=$("#pagesList");box.innerHTML="";state.pages.forEach((p,i)=>{const row=document.createElement("div");row.className="page-item"+(p.id===state.activePage?" active":"");row.innerHTML=`<span class="page-icon">${i?"□":"⌂"}</span><button class="page-name" type="button">${esc(p.name)}</button><button class="page-menu" type="button">⋯</button>`;row.querySelector(".page-name").onclick=()=>{state.activePage=p.id;state.selected=null;state.selectedElement=null;render();dirty()};row.querySelector(".page-name").ondblclick=()=>openRename(p);row.querySelector(".page-menu").onclick=e=>{e.stopPropagation();showPageMenu(row,p)};box.appendChild(row)})}
function showPageMenu(anchor,p){closeMenus();const r=anchor.getBoundingClientRect(),m=document.createElement("div");m.className="wb-context-menu";m.style.left=`${Math.min(r.right+6,innerWidth-190)}px`;m.style.top=`${Math.min(r.top,innerHeight-150)}px`;m.innerHTML=`<button data-act="rename">Rename page</button><button data-act="duplicate">Duplicate page</button><button data-act="delete" class="danger">Delete page</button>`;m.onclick=e=>{const a=e.target.dataset.act;if(a==="rename")openRename(p);if(a==="duplicate")duplicatePage(p);if(a==="delete")deletePage(p);closeMenus()};document.body.appendChild(m)}
function renderCanvas(){const c=$("#sitePage");c.innerHTML="";const p=active();p.sections.forEach(s=>{const el=document.createElement("section");el.className="site-section"+(state.selected===s.id?" selected":"");el.dataset.section=s.id;styleSection(el,s);el.innerHTML=`<span class="section-handle">${esc(s.type.toUpperCase())}<span class="section-actions"><button data-sec-act="up">↑</button><button data-sec-act="down">↓</button><button data-sec-act="duplicate">⧉</button><button data-sec-act="delete">×</button></span></span>`+sectionMarkup(s);el.classList.add(s.type==="header"?"site-header-section":s.type==="hero"?"site-hero":s.type==="products"?"product-section-edit":s.type==="footer"?"site-footer-section":"feature-section-edit");
if(s.type==="header"){const nav=el.querySelector(".site-nav-edit");state.pages.forEach(q=>{const b=document.createElement("button");b.type="button";b.textContent=q.name;b.dataset.navPage=q.id;b.onclick=e=>{e.stopPropagation();state.activePage=q.id;state.selected=null;state.selectedElement=null;render();dirty()};nav.appendChild(b)})}
if(s.image){const img=el.querySelector(".uploaded-image");if(img)img.src=s.image}
el.querySelectorAll("[data-edit-text]").forEach(n=>{n.dataset.section=s.id;const ts=s.textStyles?.[n.dataset.key];if(ts){if(ts.size)n.style.fontSize=ts.size+"px";if(ts.weight)n.style.fontWeight=ts.weight;if(ts.color)n.style.color=ts.color}n.addEventListener("click",e=>{e.stopPropagation();setSelected(s.id,n.dataset.key)});n.addEventListener("dblclick",e=>{e.stopPropagation();editTextNode(n,s.id)})});
el.querySelectorAll("[data-link=true]").forEach(b=>{b.dataset.section=s.id;b.addEventListener("click",e=>{e.stopPropagation();setSelected(s.id,b.dataset.linkKey)});b.addEventListener("contextmenu",e=>{e.preventDefault();if(linkTarget(s.id,b.dataset.linkKey))goToTarget(s.id,b.dataset.linkKey);else showContext(s.id,b.dataset.linkKey,e.clientX,e.clientY)})});
el.querySelectorAll("[data-sec-act]").forEach(b=>b.addEventListener("click",e=>{e.stopPropagation();const a=b.dataset.secAct;if(a==="delete")deleteSection(s.id);if(a==="duplicate")duplicateSection(s.id);if(a==="up")moveSection(s.id,-1);if(a==="down")moveSection(s.id,1)}));
el.addEventListener("click",e=>{if(e.target.closest("[data-edit-text],[data-link=true],[data-sec-act],input,textarea,details"))return;setSelected(s.id,null)});el.addEventListener("contextmenu",e=>{if(e.target.closest("[data-edit-text],[data-link=true],input,textarea,details"))return;e.preventDefault();showContext(s.id,null,e.clientX,e.clientY)});
const imgInput=el.querySelector(".section-image-input"),drop=el.querySelector(".image-drop");if(imgInput)imgInput.addEventListener("change",e=>readImage(e.target.files?.[0],s.id));if(drop){["dragenter","dragover"].forEach(ev=>drop.addEventListener(ev,e=>{e.preventDefault();drop.classList.add("dragging")}));["dragleave","drop"].forEach(ev=>drop.addEventListener(ev,e=>{e.preventDefault();drop.classList.remove("dragging")}));drop.addEventListener("drop",e=>readImage(e.dataTransfer.files?.[0],s.id))}c.appendChild(el)})}
function moveSection(id,dir){const a=active().sections,i=a.findIndex(x=>x.id===id);if(i<1||i===a.length-1)return;const j=i+dir;if(j<1||j>=a.length-1)return;commit();[a[i],a[j]]=[a[j],a[i]];state.selected=id;dirty();render();toast("Section moved")}
function showContext(secId,key,x=0,y=0){closeMenus();const target=key?linkTarget(secId,key):"",m=document.createElement("div");m.className="wb-context-menu";m.style.left=`${Math.min(x||240,innerWidth-210)}px`;m.style.top=`${Math.min(y||160,innerHeight-190)}px`;m.innerHTML=`${key?`<button data-cmd="edit">Edit text / properties</button><button data-cmd="open">${target?"Open target page":"Set target page"}</button>`:""}<button data-cmd="duplicate">Duplicate section</button><button data-cmd="delete" class="danger">Delete</button>`;m.onclick=e=>{const c=e.target.dataset.cmd;if(c==="edit")setSelected(secId,key);if(c==="open"){if(target)goToTarget(secId,key);else setSelected(secId,key)}if(c==="duplicate")duplicateSection(secId);if(c==="delete")deleteSection(secId);closeMenus()};document.body.appendChild(m)}
function renderInspector(){const root=$("#inspectorContent");root.innerHTML="";const body=document.createElement("div");body.className="inspector-body";root.appendChild(body);
if(tab==="style"){body.innerHTML=`<div class="inspector-block"><div class="inspector-title"><strong>Global styles</strong><span>Site</span></div><div class="field-stack"><div><label class="field-label">Color palette</label><div class="swatch-row" id="palettes"></div></div><div><label class="field-label">Heading font</label><select class="select-control" id="headingFont"><option>Inter</option><option>DM Sans</option><option>Manrope</option><option>Playfair Display</option><option>Space Grotesk</option></select></div><div><label class="field-label">Body font</label><select class="select-control" id="bodyFont"><option>Inter</option><option>DM Sans</option><option>Manrope</option><option>Source Sans 3</option></select></div></div></div><div class="inspector-block"><div class="inspector-title"><strong>Canvas background</strong><span>Theme</span></div><div class="swatch-row" id="bgSwatches"><button class="swatch-btn" data-bg="#ffffff" style="background:#fff"></button><button class="swatch-btn" data-bg="#f6f7fb" style="background:#f6f7fb"></button><button class="swatch-btn" data-bg="#18171d" style="background:#18171d"></button><button class="swatch-btn" data-bg="#f3edff" style="background:#f3edff"></button></div></div><div class="inspector-block"><div class="inspector-title"><strong>Quick spacing</strong><span>Whole site</span></div><input class="range-control" id="globalSpacing" type="range" min="16" max="100" value="48"><div class="range-readout"><span>Compact</span><b id="globalSpacingValue">48 px</b><span>Airy</span></div></div>`;
const pr=$("#palettes");palettes.forEach(p=>{const b=document.createElement("button");b.className="swatch-btn"+(state.palette===p.name?" active":"");b.title=p.name;b.style.background=`linear-gradient(135deg,${p.accent} 0 25%,${p.soft} 25% 50%,${p.bg} 50% 75%,${p.text} 75%)`;b.onclick=()=>{commit();state.palette=p.name;state.accent=p.accent;dirty();render();toast(`${p.name} palette applied`)};pr.appendChild(b)});
$("#globalSpacing").oninput=e=>{$("#globalSpacingValue").textContent=`${e.target.value} px`;state.pages.forEach(p=>p.sections.forEach(s=>{p.sectionStyles??={};p.sectionStyles[s.id]??={...defaults[s.type]};p.sectionStyles[s.id].padding=+e.target.value}));dirty();renderCanvas()};$("#globalSpacing").onchange=()=>{commit();save()};
$$("[data-bg]").forEach(b=>b.onclick=()=>{commit();state.siteBg=b.dataset.bg;dirty();render();toast("Background updated")});
}else{const s=selected();if(!s){body.innerHTML='<div class="property-empty"><strong>Select an element</strong>Click a section, text or button on the canvas. Right-click for quick actions.</div>';return}const st=secStyle(s),key=state.selectedElement,isText=!!key&&!key.startsWith("hero-")&&!key.startsWith("cta")&&!key.startsWith("products-"),isButton=!!key&&(key.startsWith("hero-")||key.startsWith("cta")||key.startsWith("products-"));
body.innerHTML=`${isButton?`<div class="inspector-block"><div class="inspector-title"><strong>Button label</strong><span>Text</span></div><input class="text-edit-control" id="buttonLabel" value="${esc(s.buttonTexts?.[key]||"")}" placeholder="Button text"></div>`:""}<div class="inspector-block"><div class="inspector-title"><strong>Spacing</strong><span>${st.padding}px / ${st.minHeight}px</span></div><div class="field-stack"><div><label class="field-label">Section height</label><input class="range-control" id="heightRange" type="range" min="120" max="900" value="${st.minHeight}"><div class="range-readout"><span>Short</span><b id="heightValue">${st.minHeight}px</b><span>Tall</span></div></div><div><label class="field-label">Top / bottom space</label><input class="range-control" id="padRange" type="range" min="8" max="140" value="${st.padding}"><div class="range-readout"><span>Tight</span><b id="padValue">${st.padding}px</b><span>Airy</span></div></div></div></div><div class="inspector-block"><div class="inspector-title"><strong>${isText?"Text":"Section"} properties</strong><span>${key||s.type}</span></div>${isText?`<div class="field-stack"><div><label class="field-label">Font size</label><input class="number-control" id="fontSize" type="number" min="8" max="120" value="${s.textStyles?.[key]?.size||18}"></div><div><label class="field-label">Weight</label><select class="select-control" id="fontWeight"><option value="400">400</option><option value="500">500</option><option value="600" selected>600</option><option value="700">700</option><option value="800">800</option><option value="900">900</option></select></div><div><label class="field-label">Color</label><input class="color-input" id="fontColor" type="color" value="${s.textStyles?.[key]?.color||"#16151b"}"></div></div>`:`<div class="field-stack"><div><label class="field-label">Width</label><select class="select-control" id="sectionWidth"><option value="center">Centered</option><option value="wide">Wide</option><option value="full">Full bleed</option></select></div></div>`}</div>${key?`<div class="inspector-block"><div class="inspector-title"><strong>Page action</strong><span>Links</span></div><div class="link-row"><select class="select-control" id="linkSelect"><option value="">No target</option>${state.pages.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join("")}</select><button class="add-square" id="newPageFromLink" type="button">+</button></div><p class="helper-text">Right-click a linked button or text to open its target page.</p></div>`:""}<div class="inspector-block"><div class="inspector-title"><strong>Arrange</strong><span>Canvas</span></div><div class="action-row"><button class="mini-action" id="dupSection">Duplicate</button><button class="mini-action danger-action" id="delSection">Delete</button></div></div>`;
const buttonLabel=$("#buttonLabel");if(buttonLabel){buttonLabel.oninput=e=>{s.buttonTexts??={};s.buttonTexts[key]=e.target.value;dirty();renderCanvas()};buttonLabel.onchange=()=>{commit();save()}}
const link=$("#linkSelect");if(link){link.value=linkTarget(s.id,key);link.onchange=()=>applyPageLink(s.id,key,link.value);$("#newPageFromLink").onclick=openPageModal}
$("#heightRange").oninput=e=>{active().sectionStyles??={};active().sectionStyles[s.id]??={};active().sectionStyles[s.id].minHeight=+e.target.value;$("#heightValue").textContent=e.target.value+"px";dirty();renderCanvas()};$("#heightRange").onchange=()=>{commit();save();renderInspector()};
$("#padRange").oninput=e=>{active().sectionStyles??={};active().sectionStyles[s.id]??={};active().sectionStyles[s.id].padding=+e.target.value;$("#padValue").textContent=e.target.value+"px";dirty();renderCanvas()};$("#padRange").onchange=()=>{commit();save();renderInspector()};
if($("#sectionWidth")){ $("#sectionWidth").value=active().sectionStyles?.[s.id]?.width||"center";$("#sectionWidth").onchange=e=>{commit();active().sectionStyles??={};active().sectionStyles[s.id]??={};active().sectionStyles[s.id].width=e.target.value;dirty();render()}}
if($("#fontSize"))$("#fontSize").onchange=e=>updateTextStyle(s,key,"size",+e.target.value);if($("#fontWeight"))$("#fontWeight").onchange=e=>updateTextStyle(s,key,"weight",+e.target.value);if($("#fontColor"))$("#fontColor").oninput=e=>updateTextStyle(s,key,"color",e.target.value);
$("#dupSection").onclick=()=>duplicateSection(s.id);$("#delSection").onclick=()=>deleteSection(s.id);
}}
function updateTextStyle(s,key,prop,val){commit();s.textStyles??={};s.textStyles[key]??={};s.textStyles[key][prop]=val;dirty();render()}
function render(){renderPages();renderCanvas();renderInspector();$("#projectNameBtn").innerHTML=esc(state.projectName)+" <span>⌄</span>";$("#breadcrumbProject").textContent=state.projectName;$("#breadcrumbPage").textContent=active().name;$("#siteFrame").className="site-frame "+state.device;$("#siteFrame").style.transform=`scale(${state.zoom})`;$("#zoomLabel").textContent=Math.round(state.zoom*100)+"%";document.documentElement.style.setProperty("--wb-purple",state.accent);$("#sitePage").style.background=state.siteBg||"#fff";$$('.device-btn').forEach(b=>b.classList.toggle("active",b.dataset.device===state.device))}
function preview(){const out=$("#previewSite");out.innerHTML="";const clone=$("#sitePage").cloneNode(true);clone.querySelectorAll(".section-handle").forEach(x=>x.remove());clone.querySelectorAll(".selected").forEach(x=>x.classList.remove("selected"));clone.querySelectorAll("[contenteditable]").forEach(x=>x.removeAttribute("contenteditable"));out.appendChild(clone);$("#previewOverlay").classList.remove("hidden")}
$$(".inspector-tab").forEach(b=>b.onclick=()=>{tab=b.dataset.tab;$$('.inspector-tab').forEach(x=>x.classList.toggle("active",x===b));renderInspector()});
$("#addPageBtn").onclick=openPageModal;$("#createPageConfirm").onclick=createPage;$("#renamePageConfirm").onclick=renamePage;$$('[data-close-modal]').forEach(b=>b.onclick=closeModals);$$('.modal-backdrop').forEach(m=>m.onclick=e=>{if(e.target===m)closeModals()});
$("#undoBtn").onclick=undo;$("#redoBtn").onclick=redo;$("#previewBtn").onclick=preview;$("#closePreviewBtn").onclick=()=>$("#previewOverlay").classList.add("hidden");$("#publishBtn").onclick=()=>{save();toast("Saved locally — publishing connection comes later")};
$("#projectNameBtn").onclick=()=>{const n=prompt("Website name",state.projectName);if(n?.trim()){commit();state.projectName=n.trim();dirty();render()}};
$("#zoomIn").onclick=()=>{state.zoom=Math.min(1.5,+(state.zoom+.1).toFixed(2));render()};$("#zoomOut").onclick=()=>{state.zoom=Math.max(.5,+(state.zoom-.1).toFixed(2));render()};$("#zoomReset").onclick=()=>{state.zoom=1;render()};
$$('.device-btn').forEach(b=>b.onclick=()=>{state.device=b.dataset.device;render()});
const map={text:"about",button:"cta",image:"image",video:"about",divider:"divider",spacer:"spacer",icon:"features",social:"features",products:"products",faq:"faq",contact:"contact",html:"about"};
$$('.element-tile').forEach(b=>b.onclick=()=>addSection(map[b.dataset.element]||"about"));$$('.template-card').forEach(b=>b.onclick=()=>addSection(b.dataset.template));
$("#elementSearch").oninput=e=>{const q=e.target.value.toLowerCase();$$('.element-tile').forEach(b=>b.style.display=b.textContent.toLowerCase().includes(q)?"":"none")};$("#clearElementSearch").onclick=()=>{$("#elementSearch").value="";$$('.element-tile').forEach(b=>b.style.display="")};$("#viewAllTemplates").onclick=()=>toast("Template library is ready for more packs");
document.addEventListener("click",e=>{if(!e.target.closest(".wb-context-menu,.page-menu"))closeMenus()});document.addEventListener("contextmenu",e=>{if(e.target.closest(".canvas-edit-text,[data-edit-text]")){e.preventDefault();const n=e.target.closest(".canvas-edit-text,[data-edit-text]");showContext(n.dataset.section,n.dataset.key,e.clientX,e.clientY)}});
document.addEventListener("keydown",e=>{if(e.key==="Escape"){closeMenus();closeModals()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="z"){e.preventDefault();e.shiftKey?redo():undo()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="y"){e.preventDefault();redo()}if((e.key==="Delete"||e.key==="Backspace")&&state.selected&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName)&&!document.activeElement.isContentEditable){deleteSection(state.selected)}});
render();
})();